
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: portal
      POSTGRES_PASSWORD: portalpass
      POSTGRES_DB: transport
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/src/sql:/docker-entrypoint-initdb.d:ro
    networks:
      - portal-net

  backend:
    build: ./backend
    restart: on-failure
    env_file: ./backend/.env
    depends_on:
      - postgres
    ports:
      - '4000:4000'
    networks:
      - portal-net

  frontend:
    build: ./frontend
    restart: on-failure
    environment:
      - NEXT_PUBLIC_API_URL=http://172.90.90.58/api
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - portal-net

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend
    networks:
      - portal-net

volumes:
  pgdata:

networks:
  portal-net:
    driver: bridge